### PR TITLE
Customize bash prompt

### LINKED ISSUE #5: Do we want the git branch on the command line?
image

Would we like something like:

- current branch
- "dirty" marker

I find it to be nice personally, but maybe just distracting for students?

Thoughts @raghubetina @jelaniwoods?

### PR DESCRIPTION
**Pull request by jelaniwoods**
Resolves #5 

This PR changes the default bash prompt to minimal and mimic thoughbot's suggested prompt

```
current-folder current-branch %
```

This commit also fixes some issues with the basic Gitpod configuration.

### CODE REVIEW

**Comment by bpurinton** [comment]
@jelaniwoods might be jumping in too soon here, but I wanted to have a look. As it's set right now, there is no branch info provided on the command line (this is a Codespaces launch of this PR):

image

**Comment by jelaniwoods** [comment]
It looks like maybe codespaces might make some overrides to `.bashrc` file from the image that prevent the fix I made from working. I know that adding this:
```
parse_git_branch() {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/'
}

PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\W \[\033[01;34m\]$(parse_git_branch)\[\033[00m\] % '

```
to the bottom of `.bashrc` and running `source ~/.bashrc` does put the branch in the prompt

image

It's also possible I didn't actually build the image after making edits to the Dockerfile, or that I accidentally escaped the the branch name so it doesn't display.

**Comment by bpurinton** [comment]
@jelaniwoods wondering what the status of this is. Is it the case that you just need to rebuild the image to get the branch name on the command prompt? Current build is `jelaniwoods/appdev2023-rails-template-test-6`. And I wonder if we want to remove that `*-test-X` from the build name?

**Comment by jelaniwoods** [comment]
Oops, I thought I finished this. ~~Maybe I just didn't push the changes I made 🤔~~

It looks like my custom bash prompt is being overwritten for some reason.

> And I wonder if we want to remove that *-test-X from the build name?

I'm only doing this until the image finalizes. There was an issue in the past where Gitpod would not always pull the very latest version of an image if you were making rapid changes to it. I'm unsure if this is the case with codespaces.

**Comment by jelaniwoods** [comment]
@bpurinton I think this should be working now. Can you verify

**Comment by bpurinton** [comment]
@jelaniwoods Verified. LGTM! You can merge it

**Pull request merged**
