### PR TITLE
Update bin/server to bin/dev

### PR DESCRIPTION
**Pull request by bpurinton**
I think we want to do a simple renaming here. However, in addition, do we want to remove the stuff for killing a currently running server instance? The goal here is to simplify the startup command as much as possible because we may show Phase 1 students the `ruby app.rb` to `rackup --port=3000` to `bin/dev` transition in the context of creating a Sinatra app and the current lines of code are a bit tougher to explain.

I tested and it looks like you get a nice little message informing you the server is already running without the kill stuff:

image

### CODE REVIEW

**Review by jelaniwoods — COMMENTED** [review]
> I tested and it looks like you get a nice little message informing you the server is already running without the kill stuff:

@bpurinton 

I can't find the conversation right now, but the additional lines to `bin/server` are to automatically kill the process running the server and delete stale PID file.

At the time it was added, it was observed that:
- students never remember / want to delete a stale PID file
- students very often tried to start more than one server at a time, and would be confused by the error message
- Gitpod would sometimes keep a stale PID file when a workspace would shutdown after a timeout. This made the server not start and also confused students. I'm unsure if this still happens or happens with codespaces.

Was removing the auto-kill server code something you already discusses with Raghu?

**Comment by bpurinton** [comment]
Raghu and I did discuss it this morning and he was wondering about removing those lines. I'm sure there was a good (if somewhat forgotten?) reason for those lines to kill stale processes. Although, there is supposedly going to be more focus early on in the configuration and launching of an app in the Sinatra changeover, and with Codespaces the students will be using the "Ports" tab in the terminal view.

If we aren't comfortable deleting yet, we can keep this PR open and discuss / think about it more as I'm testing and building out the Sinatra stuff.

**Comment by bpurinton** [comment]
@jelaniwoods I'd like to start the Rails 7 changeover based on this template. I just tested this PR. In Codespaces, when I run `bin/dev` without the block of PID-killing code, a `tmp/pids/server.pid` file is made. If I try to run `bin/dev` again, I get a nice, short message that the process is already running. If I end the process, `tmp/pids/server.pid` is automatically removed (without the need for the block of code in `bin/dev`).

**Comment by jelaniwoods** [comment]
> Gitpod would sometimes keep a stale PID file when a workspace would shutdown after a timeout. This made the server not start and also confused students.

@bpurinton this was one of my main concerns about removing the current setup. In codespaces, if you start a server and then shutdown the codespace (**without** stopping the server), can you immediately start the server when you reopen the codespace? or is there a stale PID file that would need to be deleted first?

**Comment by bpurinton** [comment]
> > Gitpod would sometimes keep a stale PID file when a workspace would shutdown after a timeout. This made the server not start and also confused students.
> 
> @bpurinton this was one of my main concerns about removing the current setup. In codespaces, if you start a server and then shutdown the codespace (**without** stopping the server), can you immediately start the server when you reopen the codespace? or is there a stale PID file that would need to be deleted first?

@jelaniwoods Just tested. You can close a workspace (completely or just x-ing out) and reopen or restart it. If the PID file is there and you start a new server, the ID in the file is automatically updated to a new value. No need to delete anything.

_Maybe_ this is still a problem on Gitpod, but I'm kind of in favor or removing it regardless since Codespaces is going to be the suggested path that most students will take.

**Review by jelaniwoods — APPROVED** [review]
I'm also not concerned with how Gitpod handles the PID, but I did want to note the potential pain points that we faced previously. Since you've already cleared this with Raghu merge when ready.

**Pull request merged**
